
[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# Handle React Router's client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variable configuration
[context.production.environment]
  VITE_APP_DOMAIN = "https://linok.me"

[context.development.environment]
  VITE_APP_DOMAIN = "http://localhost:8080"

# Remove dependence on netlify-plugin-inline-functions-env
# and set up standard environment variable handling
